development:
  adapter: postgresql
  encoding: unicode
  database: rails_react
  pool: 5
  username: postgres
  password: Aravipost

test:
  adapter: postgresql
  encoding: unicode
  database: rails_react
  pool: 5
  username: postgres
  password: Aravipost